# Brewfile
# https://github.com/Homebrew/homebrew-bundle
# tap "homebrew/cask"
tap "homebrew/cask-fonts"

# set arguments for all 'brew install --cask' commands
cask_args appdir: "~/Applications", require_sha: true

# Install core packages
brew "coreutils" 
brew "wget"        
brew "findutils"   
brew "gnupg" if OS.mac?
brew "tree"      
brew "dos2unix"   

# Others
#brew "mysql@5.6", restart_service: true, link: true, conflicts_with: ["mysql"] # MySQL 5.6
brew "tmux" 
brew "jq"   
brew "pre-commit" # Install pre-commit package manager (https://pre-commit.com/#install)

# Themes & Fonts
brew "spaceship"           # Theme, https://github.com/spaceship-prompt/spaceship-prompt
brew "font-hack-nerd-font" # Fonts, https://github.com/ryanoasis/nerd-fonts